amazon:
  access:
    key: <YOUR_ACCESS_KEY>
    secret-key: <YOUR_SECRET_KEY>
  region: us-east-1
  end-point:
    url: dynamodb.us-east-1.amazonaws.com

server:
  port: 9001

spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: group_id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      properties:
        schema:
          registry:
            url: http://localhost:8081